//! **The schemas this repository ships, and the reader that embeds them.**
//!
//! An integration test rather than a unit one because the claim spans the tool and the
//! files beside it: `schemas/` is what `fjord create --schema` is pointed at, what the
//! .NET clients state independently, and what `sample_schema` compiles in — so a change
//! to one of them that nothing here notices is a change somebody finds out about at a
//! handshake.

use fjord_schema::{fingerprint, syntax::resolve};

/// **The embedded reader follows imports**, and it is handed more than one file here so
/// that it is not only ever handed one.
///
/// `sample_schema::SOURCES` holds a single entry today, so nothing in the production
/// path exercises the multi-file case — and a resolving reader that has only ever seen
/// one file is a reader whose import handling is untested. This hands the same function
/// a genuine two-file set: an entry that declares nothing but an import, and the file
/// that answers it.
///
/// The two assertions are what would fail on the two plausible wrong implementations:
/// lowering only the entry (no `dep.Thing`, and `app.Use` unresolvable), and lowering
/// each file separately (`app.Use`'s reference could not resolve across the boundary).
#[test]
fn the_embedded_reader_follows_imports() {
    const ENTRY: &str = "schema app { import dep\n predicate Use : { of : dep.Thing } }";
    const DEP: &str = "schema dep { predicate Thing : string }";

    let resolved = resolve::resolve_from([("app.sigla", ENTRY), ("dep.sigla", DEP)])
        .expect("a two-file schema resolves");

    assert_eq!(resolved.files.len(), 2, "{:?}", resolved.files);

    let names: Vec<&str> = (0..resolved.schema.len())
        .filter_map(|index| {
            resolved
                .schema
                .get(fjord_schema::schema::PredicateId(index as u32))?
                .name()
        })
        .collect();

    // Sorted by qualified name, `app` before `dep` — both files' predicates, in one
    // schema, numbered together.
    assert_eq!(names, ["app.Use", "dep.Thing"]);
}

/// **A schema split across files is fingerprint-identical to the same declarations in
/// one**, so the split W6 lands costs nothing at the predicate level.
///
/// The mechanism is in the tree rather than in luck: an alias is expanded at lowering,
/// so its name never reaches a `PredicateTy`, and a `Predicate` carries no file for the
/// canonical form to read. This is that stated as a test, because every later schema
/// file in `schemas/` rests on it.
#[test]
fn moving_a_declaration_into_an_imported_file_moves_no_fingerprint() {
    let together = resolve::resolve_from([(
        "one.sigla",
        "schema app { type Flag = { no : {} = 0 | yes : {} = 1 }\n \
         predicate P : { flag : Flag } }",
    )])
    .expect("one file resolves");

    let apart = resolve::resolve_from([
        (
            "entry.sigla",
            "schema app { import base\n predicate P : { flag : base.Flag } }",
        ),
        (
            "base.sigla",
            "schema base { type Flag = { no : {} = 0 | yes : {} = 1 } }",
        ),
    ])
    .expect("two files resolve");

    assert_eq!(
        fingerprint::of(&together.schema),
        fingerprint::of(&apart.schema),
        "moving a named type into an imported file moved the schema fingerprint"
    );
    assert_eq!(
        fingerprint::identity(&together.schema).predicates(),
        fingerprint::identity(&apart.schema).predicates(),
        "moving a named type into an imported file moved a predicate fingerprint"
    );
}

/// **Every schema this repository ships has its fingerprint recorded here.**
///
/// A shipped schema's number is what a client carries as a constant, so an accidental
/// edit to one is a refused handshake at somebody's site — a red suite is cheaper. The
/// golden is regenerated by reading the failure, never by hand.
#[test]
fn every_shipped_schema_has_a_recorded_fingerprint() {
    let root = concat!(env!("CARGO_MANIFEST_DIR"), "/../../schemas");

    let mut recorded: Vec<(String, String)> = std::fs::read_dir(root)
        .expect("the schemas directory")
        .map(|entry| entry.expect("a directory entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "sigla"))
        .map(|path| {
            let name = path
                .file_name()
                .expect("a file name")
                .to_string_lossy()
                .into_owned();
            let resolved = resolve::resolve(&path, &[std::path::PathBuf::from(root)])
                .unwrap_or_else(|reason| panic!("{name} does not resolve:\n{reason}"));

            (name, format!("{:#018x}", fingerprint::of(&resolved.schema)))
        })
        .collect();

    recorded.sort();

    let expected = [
        ("code.sigla", "0xb08eea634e866a75"),
        ("config.sigla", "0xac3c414ab7ff574f"),
        ("demo.sigla", "0x026d61be0818f394"),
    ];

    assert_eq!(
        recorded
            .iter()
            .map(|(name, hash)| (name.as_str(), hash.as_str()))
            .collect::<Vec<_>>(),
        expected,
        "a shipped schema's fingerprint moved, or a schema arrived without one"
    );
}
